const STRING = {
    login: 'Login',
    dont_have_an_account: "Don't have an account? ",
    register: 'Register',
    lets: 'Let’s ',
    sign_in: 'Sign In',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot Password?',
    or: 'OR',
    create_an_account: 'Create an account',
    next: 'Next',
    full_name: 'Full Name',
    confirm_password: 'Confirm Password',
    agree_to_terms_conditions: 'Agree to the Terms & Condition',
    forgot: 'Forgot ',
    reset: 'Reset ',
    continue: 'Continue',
    remember_your_password: 'Remember your Password? ',
    login_insted: 'Login Instead',
    set_password: 'Set Password',
    add: 'Add ',
    your: 'your ',
    location: 'Location',
    you_can_edit_this_later_on_your_account_setting: "You can edit this later on your account setting.",
    select_on_map: 'select on map',
    location_detail: 'Location detail',
    select_your_location_to_find_relevant_properties_near_you: "Select your location to find relevant properties near you.",
    find_location: 'Find location',
    skip: 'Skip',
    select_your_preferable: 'Select your preferable ',
    property_type: 'Property Type',
    add_budget: 'Add Budget',
    fiil_your: 'Fill your',
    information_below: 'Information below',
    submit: 'Submit',
    phone_number: 'Phone number',
    account: 'Account ',
    successfully: 'successfully',
    created: 'created',
    finish: 'Finish',
    search_here: 'Search here',
    nearby_listing: 'Nearby Listings',
    available: 'Available',
    bathrooms: 'bathrooms',
    bedrooms: 'bedrooms',
    more: 'More',
    sold: 'Sold',
    luxury: 'Luxury',
    share: 'Share',
    description: 'Description',
    gallery: 'Gallery',
    facilities: 'Facilities',
    location_and_public_facility: 'Location & Public Facilities',
    view_all_on_map: 'View all on map',
    request_more_info: 'Request More Info',
    total_price: 'Total Price',
    from_your_location: 'from your location',
    write_comment: 'Write comment..',
    search_results: 'Search results',
    found: 'Found',
    estates: 'estates',
    search: 'Search',
    not_found: 'not found',
    search_not_found_error: 'Sorry, we can’t find the property you are looking for Maybe,\n a little spelling mistake?',
    filter: 'Filter',
    price_range: 'Price Range',
    amenities: 'Amenities',
    property_size: 'Property size',
    select: 'Select',
    apply_filter: 'Apply Filter',
    bathrooms_capital: 'Bathrooms',
    bedrooms_capital: 'Bedrooms',
    style: 'Style',
    colour: 'Color',
    furniture: 'Furniture',
    favourite_property: 'Favorite Properties',
    remove_from_favourite: 'Remove from Favorite?',
    yes_remove: 'Yes, Remove',
    cancel: 'Cancel',
    all_chats: 'All Chats',
    say_something: 'Say something',
    are_you_sure_want_to: 'Are you sure want to ',
    delete: 'delete',
    all_your_chat: 'all your chat?',
    this_action_cant_be_undo: 'This action can’t be undo',
    delete_capital: 'Delete',
    today: 'Today',
    older_notifications: 'Older notifications',
    just_messaged_you: 'Just messaged you. ',
    check_the_message_in: 'Check the message in\n',
    message: 'message ',
    tab: 'tab.',
    profile: 'Profile',
    edit_profile: 'Edit Profile',
    privacy_policy: 'Privacy Policy',
    term_conditions: 'Terms & Conditions',
    support: 'Support',
    logout_capital: 'Logout',
    logout: 'logout',
    the_account: 'the account?',
    update: 'Update',
    near_by_you: 'Nearby you',
    cant_found_real_estate_nearby_you: `Can't found real estate nearby you`,
    already_have_an_account:'Already have an account? '
}

export { STRING }