const STRING = {
    login: 'Login',
    dont_have_an_account: "Don't have an account? ",
    register: 'Register',
    lets: 'Let’s ',
    sign_in: 'Sign In',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot Password?',
    or: 'OR',
    create_an_account: 'Create an account',
    next: 'Next',
    full_name: 'Full Name',
    confirm_password: 'Confirm Password',
    agree_to_terms_conditions: 'Agree to the Terms & Condition',
    forgot: 'Forgot ',
    reset: 'Reset ',
    continue: 'Continue',
    remember_your_password: 'Remember your Password? ',
    login_insted: 'Login Instead',
    set_password: 'Set Password',
    add: 'Add ',
    your: 'your ',
    location: 'Location',
    you_can_edit_this_later_on_your_account_setting: "You can edit this later on your account setting.",
    select_on_map: 'select on map',
    location_detail: 'Location detail',
    select_your_location_to_find_relevant_properties_near_you: "Select your location to find relevant properties near you.",
    find_location: 'Find location',
    skip: 'Skip',
    select_your_preferable: 'Select your preferable ',
    property_type: 'Property Type',
    add_budget: 'Add Budget',
    fiil_your: 'Fill your',
    information_below: 'Information below',
    submit: 'Submit',
    phone_number: 'Phone number',
    account: 'Account ',
    successfully: 'successfully',
    created: 'created',
    finish: 'Finish',
    search_here: 'Search here',
    nearby_listing: 'Nearby Listings',
    available: 'Available',
    bathrooms: 'bathrooms',
    bedrooms: 'bedrooms',
    more: 'More',
    sold: 'Sold',
    luxury: 'Luxury',
    share: 'Share',
    description: 'Description',
    gallery: 'Gallery',
    facilities: 'Facilities',
    location_and_public_facility: 'Location & Public Facilities',
    view_all_on_map: 'View all on map',
    request_more_info: 'Request More Info',
    total_price: 'Total Price',
    from_your_location: 'from your location',
    write_comment: 'Write comment..'
}

export { STRING }